openapi: 3.0.0
info:
  title: ContactManager API
  version: 1.0.0

servers:
  - url: http://localhost:8080/

paths:
  /contacts:
    post:
      summary: Create a new contact
      operationId: createContact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactDTO'
      responses:
        '201':
          description: Contact created successfully
        '400':
          description: Bad request

    get:
      summary: Search contacts
      operationId: searchContacts
      parameters:
        - name: firstName
          in: query
          description: First name of the contact
          schema:
            type: string
        - name: lastName
          in: query
          description: Last name of the contact
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContactDTO'
        '400':
          description: Bad request

  /contacts/{contactId}:
    put:
      summary: Update contact details
      operationId: updateContact
      parameters:
        - name: contactId
          in: path
          description: ID of the contact to be updated
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactDTO'
      responses:
        '200':
          description: Contact updated successfully
        '404':
          description: Contact not found

    delete:
      summary: Delete a contact
      operationId: deleteContact
      parameters:
        - name: contactId
          in: path
          description: ID of the contact to be deleted
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Contact deleted successfully
        '404':
          description: Contact not found

components:
  schemas:
    ContactDTO:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        # Add other contact details as needed
